-- SELECT
-- 'ALTER TABLE '|| table_name||' DISABLE TRIGGER ALL;'
-- FROM information_schema.tables WHERE table_schema = 'omop' ;

ALTER TABLE omop.cdm_source DISABLE TRIGGER ALL;
ALTER TABLE omop.attribute_definition DISABLE TRIGGER ALL;
ALTER TABLE omop.vocabulary DISABLE TRIGGER ALL;
ALTER TABLE omop.person DISABLE TRIGGER ALL;
ALTER TABLE omop.note_nlp DISABLE TRIGGER ALL;
ALTER TABLE omop.domain DISABLE TRIGGER ALL;
ALTER TABLE omop.concept_synonym DISABLE TRIGGER ALL;
ALTER TABLE omop.cohort DISABLE TRIGGER ALL;
ALTER TABLE omop.relationship DISABLE TRIGGER ALL;
ALTER TABLE omop.fact_relationship DISABLE TRIGGER ALL;
ALTER TABLE omop.drug_strength DISABLE TRIGGER ALL;
ALTER TABLE omop.concept_ancestor DISABLE TRIGGER ALL;
ALTER TABLE omop.observation_period DISABLE TRIGGER ALL;
ALTER TABLE omop.payer_plan_period DISABLE TRIGGER ALL;
ALTER TABLE omop.concept_relationship DISABLE TRIGGER ALL;
ALTER TABLE omop.cohort_definition DISABLE TRIGGER ALL;
ALTER TABLE omop.location DISABLE TRIGGER ALL;
ALTER TABLE omop.specimen DISABLE TRIGGER ALL;
ALTER TABLE omop.dose_era DISABLE TRIGGER ALL;
ALTER TABLE omop.visit_detail DISABLE TRIGGER ALL;
ALTER TABLE omop.death DISABLE TRIGGER ALL;
ALTER TABLE omop.procedure_occurrence DISABLE TRIGGER ALL;
ALTER TABLE omop.drug_exposure DISABLE TRIGGER ALL;
ALTER TABLE omop.note DISABLE TRIGGER ALL;
ALTER TABLE omop.condition_occurrence DISABLE TRIGGER ALL;
ALTER TABLE omop.care_site DISABLE TRIGGER ALL;
ALTER TABLE omop.provider DISABLE TRIGGER ALL;
ALTER TABLE omop.observation DISABLE TRIGGER ALL;
ALTER TABLE omop.concept_class DISABLE TRIGGER ALL;
ALTER TABLE omop.source_to_concept_map DISABLE TRIGGER ALL;
ALTER TABLE omop.cohort_attribute DISABLE TRIGGER ALL;
ALTER TABLE omop.drug_era DISABLE TRIGGER ALL;
ALTER TABLE omop.condition_era DISABLE TRIGGER ALL;
ALTER TABLE omop.cost DISABLE TRIGGER ALL;
ALTER TABLE omop.device_exposure DISABLE TRIGGER ALL;
ALTER TABLE omop.measurement DISABLE TRIGGER ALL;
ALTER TABLE omop.visit_occurrence DISABLE TRIGGER ALL;
ALTER TABLE omop.concept DISABLE TRIGGER ALL;


